<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AdminMenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admin_menu_items')->delete();
        
        \DB::table('admin_menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'label' => 'Products',
                'link' => 'products',
                'parent' => 0,
                'sort' => 0,
                'class' => NULL,
                'menu' => 1,
                'depth' => 0,
                'created_at' => '2023-12-12 00:16:46',
                'updated_at' => '2023-12-12 00:16:47',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'label' => 'Blog',
                'link' => 'blog',
                'parent' => 0,
                'sort' => 1,
                'class' => NULL,
                'menu' => 1,
                'depth' => 0,
                'created_at' => '2023-12-12 00:17:16',
                'updated_at' => '2023-12-12 00:17:16',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'label' => 'Contact',
                'link' => 'contact',
                'parent' => 0,
                'sort' => 3,
                'class' => NULL,
                'menu' => 1,
                'depth' => 0,
                'created_at' => '2023-12-12 00:17:30',
                'updated_at' => '2023-12-12 00:18:50',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'label' => 'Builds',
                'link' => 'builds',
                'parent' => 0,
                'sort' => 2,
                'class' => NULL,
                'menu' => 1,
                'depth' => 0,
                'created_at' => '2023-12-12 00:18:46',
                'updated_at' => '2023-12-12 00:18:50',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'label' => 'Privacy Policy',
                'link' => 'privacy',
                'parent' => 8,
                'sort' => 4,
                'class' => NULL,
                'menu' => 2,
                'depth' => 1,
                'created_at' => '2023-12-12 00:20:05',
                'updated_at' => '2023-12-14 16:17:53',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'label' => 'Terms & Conditions',
                'link' => 'terms',
                'parent' => 8,
                'sort' => 5,
                'class' => NULL,
                'menu' => 2,
                'depth' => 1,
                'created_at' => '2023-12-12 00:20:25',
                'updated_at' => '2023-12-14 16:17:53',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'label' => 'LINKS',
                'link' => NULL,
                'parent' => 0,
                'sort' => 0,
                'class' => NULL,
                'menu' => 2,
                'depth' => 0,
                'created_at' => '2023-12-14 16:16:12',
                'updated_at' => '2023-12-14 16:16:22',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'label' => 'HELP CENTER',
                'link' => NULL,
                'parent' => 0,
                'sort' => 3,
                'class' => NULL,
                'menu' => 2,
                'depth' => 0,
                'created_at' => '2023-12-14 16:16:20',
                'updated_at' => '2023-12-14 16:17:53',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'label' => 'Contact',
                'link' => 'contact',
                'parent' => 8,
                'sort' => 6,
                'class' => NULL,
                'menu' => 2,
                'depth' => 1,
                'created_at' => '2023-12-14 16:17:01',
                'updated_at' => '2023-12-14 16:17:53',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'label' => 'Blog',
                'link' => 'blog',
                'parent' => 7,
                'sort' => 2,
                'class' => NULL,
                'menu' => 2,
                'depth' => 1,
                'created_at' => '2023-12-14 16:17:19',
                'updated_at' => '2023-12-14 16:17:53',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'label' => 'Products',
                'link' => 'products',
                'parent' => 7,
                'sort' => 1,
                'class' => NULL,
                'menu' => 2,
                'depth' => 1,
                'created_at' => '2023-12-14 16:17:49',
                'updated_at' => '2023-12-14 16:17:56',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'label' => 'Home',
                'link' => '#',
                'parent' => 0,
                'sort' => 0,
                'class' => NULL,
                'menu' => 3,
                'depth' => 0,
                'created_at' => '2023-12-14 17:11:14',
                'updated_at' => '2023-12-14 17:11:16',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'label' => 'Privacy Policy',
                'link' => 'privacy',
                'parent' => 0,
                'sort' => 0,
                'class' => NULL,
                'menu' => 4,
                'depth' => 0,
                'created_at' => '2023-12-14 17:12:29',
                'updated_at' => '2023-12-14 17:12:31',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'label' => 'About',
                'link' => 'about',
                'parent' => 0,
                'sort' => 1,
                'class' => NULL,
                'menu' => 4,
                'depth' => 0,
                'created_at' => '2023-12-14 17:13:11',
                'updated_at' => '2023-12-14 17:13:11',
                'local' => 1,
                'development' => 1,
                'stage' => 1,
                'production' => 1,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'label' => 'About',
                'link' => 'about',
                'parent' => 0,
                'sort' => 0,
                'class' => NULL,
                'menu' => 6,
                'depth' => 0,
                'created_at' => '2023-12-15 01:51:46',
                'updated_at' => '2023-12-15 01:51:47',
                'local' => 1,
                'development' => 1,
                'stage' => 0,
                'production' => 0,
                'marketing' => 0,
                'logged_in_only' => 0,
                'icon_only_menu' => 0,
                'menu_icon_class' => NULL,
            ),
        ));
        
        
    }
}